---
title: "Term paper"
subtitle: ""
author: "Rose Hörsting & Gina Reinhard"
date: "2024-09-15"
engine: knitr
bibliography: references.bib
format: 
  html:
    toc: true
    embed-resources: true
link-citations: true
csl: "apa_7th.csl"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r include=FALSE}

library(checkdown)

```

#### **Chapter overview** {.unnumbered}

```{r load-libraries, message=FALSE}

library(tidyverse)

```

```{r import-data, message=FALSE}

raw_data <- read_csv(file = "data/raw_data.csv")

```

```{r, results=FALSE}

table(raw_data$gender)
table(raw_data$emoji_understanding)
table(raw_data$emoji_use)

```

```{r}

data <- raw_data |> 
  filter(age <= 35)

```


::: callout-tip
#### Quiz time! {.unnumbered}

1\) Test question?

```{r echo=FALSE, results="asis"}

check_question("D", options = c("A", "B", "C", "D", "E"), type = "radio", 
random_answer_order = TRUE,
button_label = "Check answer", q_id = 4,
right = "Test right!",
wrong = "Test incorrect.")

```
:::

## Conclusion
